appname: USER_SERVER
auth:
  identitykey: id
  iscaptcha: false
  key: "123456"
  maxrefresh: 24
  timeout: 24
config_path: dfadsf
dbconfig:
  automigrate: true
  databasename: business
  debug: false
  driver: postgres
  host: 192.168.3.85
  maxidleconns: "10"
  maxopenconns: "20"
  password: business
  port: "5432"
  username: business
debug: true
grpcgatewayport: "8300"
grpcport: "8200"
httpport: "8101"
jaegerendpoint: http://192.168.3.85:14268/api/traces
run_mode: unit_test
tlskey: "8300"
